name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install packages
        run: npm ci

      - name: Lint w/ ESLint
        run: npm run lint

      - name: Format w/ Prettier
        run: npm run prettier:format

      - name: Unit tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: coverage

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: build
